modLoader = "javafml"
loaderVersion = "[38,)"
issueTrackerURL = "https://github.com/multiverse-storage/issues"
license = "MIT"

[[mods]]
modId = "multiversestorage"
version = "${version}"
displayName = "Multiverse Storage"
authors = "copygirl"
description = '''
Adds storage blocks to move items between different Minecraft servers.
'''
#logoFile = ""

[[dependencies.multiversestorage]]
modId = "forge"
mandatory = true
versionRange = "[38,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.multiversestorage]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.multiversestorage]]
modId = "architectury"
mandatory = true
versionRange = "[3.2.47,)"
ordering = "AFTER"
side = "BOTH"
